<?php namespace JF;
/**

Copyright 2022 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-56b0b2
Date:    2022-06-30 08:32:22
Version: v3.1
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-56b0b2",
    "email": {
        "to": "stephane_lambert@sympatico.ca",
        "cc": "",
        "bcc": "",
        "subject": "Demande de service {AutoID}",
        "template": "",
        "fromName": "St\u00e9phane Lambert",
        "sendmail_from": "lambert.stephane@gmail.com"
    },
    "admin": {
        "users": "admin:cf4b40b374",
        "dataDelivery": "emailOnly"
    },
    "thankyou": {
        "url": "",
        "message": "Votre demande de service a \u00e9t\u00e9 envoy\u00e9e. Vous recevrez l'estimation des frais de service et les instructions pour l'envoi de votre appareil d'ici 24 heures (ouvrables). Merci !",
        "seconds": "10"
    },
    "autoResponse": {
        "includeAttachments": true,
        "subject": "",
        "template": ""
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "smtp",
    "smtp": {
        "host": "smtp.gmail.com",
        "user": "lambert.stephane@gmail.com",
        "password": "8055ggmail",
        "port": "587",
        "security": "tls",
        "debug": true
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "blue"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [
        {
            "disabled": false,
            "action": "show",
            "selector": "f14",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f13",
                    "condition": "==",
                    "value": "Autre"
                }
            ]
        },
        {
            "disabled": false,
            "action": "show",
            "selector": "f20,f21",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f19",
                    "condition": "==",
                    "value": "R\u00e9assembler et me retourner l'appareil (frais de retour applicables)"
                }
            ]
        },
        {
            "disabled": false,
            "action": "hide",
            "selector": "f14",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f13",
                    "condition": "not contains",
                    "value": "Autre"
                }
            ]
        },
        {
            "disabled": false,
            "action": "hide",
            "selector": "f20,f21",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f19",
                    "condition": "!=",
                    "value": "R\u00e9assembler et me retourner l'appareil (frais de retour applicables)"
                }
            ]
        }
    ],
    "fields": [
        {
            "label": "B\u00e9n\u00e9ficiaire",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false,
                    "responsive": true
                }
            },
            "id": "f9",
            "cid": "c34"
        },
        {
            "label": "Pr\u00e9nom",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false,
                    "responsive": true
                },
                "size": "small",
                "addon": {
                    "leftText": ""
                },
                "mainDescription": "",
                "description": "",
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Ce champ est requis."
                    },
                    "alphanumeric": {
                        "enabled": false
                    }
                },
                "placeholder": "",
                "mask": {
                    "pattern": ""
                }
            },
            "id": "f4",
            "cid": "c26"
        },
        {
            "label": "Nom",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false,
                    "responsive": true
                },
                "size": "small",
                "addon": [],
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Ce champ est requis."
                    }
                },
                "mask": {
                    "pattern": ""
                }
            },
            "id": "f5",
            "cid": "c31"
        },
        {
            "label": "Courriel",
            "field_type": "email",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false,
                    "responsive": true
                },
                "sender": true,
                "validators": {
                    "email": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true,
                        "msg": "Ce champ est requis."
                    }
                }
            },
            "id": "f6",
            "cid": "c36"
        },
        {
            "label": "T\u00e9l\u00e9phone",
            "field_type": "phone",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false,
                    "responsive": true
                },
                "sender": true,
                "placeholder": "",
                "addon": {
                    "leftIcon": ""
                },
                "validators": {
                    "pattern": {
                        "enabled": false,
                        "val": "[0-9]{3,4}[ -.]*[0-9]{3,4}[ -.]*[0-9]{4}",
                        "msg": "Invalid phone number"
                    },
                    "phonenumber": {
                        "enabled": true,
                        "msg": "V\u00e9rifiez votre num\u00e9ro de t\u00e9l\u00e9phone."
                    }
                },
                "mask": {
                    "pattern": ""
                }
            },
            "phone": {
                "validationMethod": "simple",
                "simpleFormat": "xxx-xxx-xxxx",
                "usePhoneLib": "Y",
                "preferredCountries": "ca,fr",
                "onlyCountries": "ca, fr"
            },
            "id": "f7",
            "cid": "c41"
        },
        {
            "label": "Adresse postale",
            "field_type": "address",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                }
            },
            "labelHide": false,
            "gMapApiKey": "",
            "gaCompleteEnabled": false,
            "gaCountryRestrictions": "ca, fr",
            "gaPostalCodeRestrictions": "",
            "gaLanguage": "fr",
            "showLabel": false,
            "showPlaceholder": false,
            "showDescription": true,
            "subfields": {
                "addressLine1": {
                    "order": 1,
                    "label": "Address Line1",
                    "field_options": {
                        "enabled": true,
                        "gAddressTypes": "street_number route",
                        "gAddressName": "long_name",
                        "placeholder": "1234 Main St.",
                        "description": "Num\u00e9ro et nom de rue",
                        "validators": {
                            "required": {
                                "enabled": true,
                                "msg": "This field is required."
                            }
                        }
                    }
                },
                "addressLine2": {
                    "order": 2,
                    "label": "Address Line2",
                    "field_options": {
                        "enabled": true,
                        "placeholder": "Unit 1234",
                        "description": "Apartement, suite, bureau, b\u00e2timent, r\u00e9sidence, escalier, \u00e9tage, etc.",
                        "validators": {
                            "required": {
                                "enabled": false,
                                "msg": ""
                            }
                        }
                    }
                },
                "city": {
                    "order": 3,
                    "label": "City",
                    "field_options": {
                        "enabled": true,
                        "gAddressTypes": "locality",
                        "gAddressName": "long_name",
                        "placeholder": "City",
                        "description": "Ville",
                        "validators": {
                            "required": {
                                "enabled": true,
                                "msg": "This field is required."
                            }
                        }
                    }
                },
                "state": {
                    "order": 4,
                    "label": "State \/ Province \/ Region",
                    "field_options": {
                        "enabled": true,
                        "gAddressTypes": "administrative_area_level_1",
                        "gAddressName": "long_name",
                        "placeholder": "State \/ Province \/ Region",
                        "description": "Province \/ R\u00e9gion",
                        "validators": {
                            "required": {
                                "enabled": true,
                                "msg": "This field is required."
                            }
                        }
                    }
                },
                "postalCode": {
                    "order": 5,
                    "label": "Postal \/ Zip Code",
                    "field_options": {
                        "enabled": true,
                        "gAddressTypes": "postal_code",
                        "gAddressName": "long_name",
                        "placeholder": "Postal \/ Zip Code",
                        "description": "Code postal",
                        "validators": {
                            "required": {
                                "enabled": true,
                                "msg": "This field is required."
                            }
                        }
                    }
                },
                "country": {
                    "order": 6,
                    "label": "Country",
                    "field_options": {
                        "enabled": true,
                        "gAddressTypes": "country",
                        "gAddressName": "long_name",
                        "placeholder": "Country",
                        "description": "Pays",
                        "validators": {
                            "required": {
                                "enabled": true,
                                "msg": "This field is required."
                            }
                        }
                    }
                }
            },
            "id": "f8",
            "cid": "c29"
        },
        {
            "label": "Appareil",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false,
                    "responsive": true
                }
            },
            "id": "f10",
            "cid": "c39"
        },
        {
            "label": "Apple iPhone",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false,
                    "responsive": true
                },
                "options": [
                    {
                        "label": "5",
                        "checked": false
                    },
                    {
                        "label": "5C",
                        "checked": false
                    },
                    {
                        "label": "5S",
                        "checked": false
                    },
                    {
                        "label": "6",
                        "checked": null
                    },
                    {
                        "label": "6+",
                        "checked": null
                    },
                    {
                        "label": "6S",
                        "checked": null
                    },
                    {
                        "label": "6S+",
                        "checked": null
                    },
                    {
                        "label": "SE (2016)",
                        "checked": null
                    },
                    {
                        "label": "7",
                        "checked": null
                    },
                    {
                        "label": "7+",
                        "checked": null
                    },
                    {
                        "label": "8",
                        "checked": null
                    },
                    {
                        "label": "8+",
                        "checked": null
                    },
                    {
                        "label": "X",
                        "checked": null
                    },
                    {
                        "label": "XR",
                        "checked": null
                    },
                    {
                        "label": "XS",
                        "checked": null
                    },
                    {
                        "label": "XS-MAX",
                        "checked": null
                    },
                    {
                        "label": "11",
                        "checked": null
                    },
                    {
                        "label": "11-PRO",
                        "checked": null
                    },
                    {
                        "label": "11-PRO-MAX",
                        "checked": null
                    },
                    {
                        "label": "SE (2020)",
                        "checked": null
                    },
                    {
                        "label": "12",
                        "checked": null
                    },
                    {
                        "label": "12-PRO",
                        "checked": null
                    },
                    {
                        "label": "12-PRO-MAX",
                        "checked": null
                    }
                ],
                "presetJson": "",
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Ce champ est requis."
                    }
                },
                "style": {
                    "columns": "col-1"
                }
            },
            "id": "f11",
            "cid": "c45"
        },
        {
            "label": "Incident \/ Probl\u00e8me",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false,
                    "responsive": true
                }
            },
            "id": "f12",
            "cid": "c51"
        },
        {
            "label": "Sympt\u00f4me(s)",
            "field_type": "checkboxes",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false,
                    "responsive": true
                },
                "options": [
                    {
                        "label": "Pas d'allumage (\u00e9cran noir)",
                        "checked": false
                    },
                    {
                        "label": "Pas d'amor\u00e7age (image\/visuel fig\u00e9\/persistant)",
                        "checked": false
                    },
                    {
                        "label": "Amor\u00e7age en boucle (image\/visuel r\u00e9appara\u00eet sans cesse)",
                        "checked": false
                    },
                    {
                        "label": "Pas de charge",
                        "checked": null
                    },
                    {
                        "label": "Pas d'affichage",
                        "checked": null
                    },
                    {
                        "label": "Pas de r\u00e9ponse tactile",
                        "checked": null
                    },
                    {
                        "label": "Pas de service (cellulaire)",
                        "checked": null
                    },
                    {
                        "label": "Pas d'audio",
                        "checked": null
                    },
                    {
                        "label": "Connecteur endommag\u00e9",
                        "checked": null
                    },
                    {
                        "label": "Trac\u00e9 de circuit endommag\u00e9",
                        "checked": null
                    },
                    {
                        "label": "Autre",
                        "checked": null
                    }
                ],
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)"
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)"
                    },
                    "required": {
                        "enabled": true,
                        "msg": "Ce champ est requis."
                    }
                },
                "presetJson": "",
                "mainDescription": "Plusieurs sympt\u00f4mes peuvent \u00eatre coch\u00e9s (si n\u00e9cessaire).",
                "style": {
                    "columns": "col-1"
                }
            },
            "id": "f13",
            "cid": "c56"
        },
        {
            "label": "Quel est cet \"Autre\" sympt\u00f4me ?",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false,
                    "responsive": true
                },
                "size": "small",
                "addon": [],
                "hidden": true,
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Ce champ est requis."
                    }
                }
            },
            "id": "f14",
            "cid": "c53"
        },
        {
            "label": "D\u00e9tails (si n\u00e9cessaire)",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false,
                    "responsive": true
                },
                "size": "small"
            },
            "id": "f15",
            "cid": "c58"
        },
        {
            "label": "Pr\u00e9c\u00e9dent l'apparition du (des) sympt\u00f4me(s), l'appareil a-t-il \u00e9t\u00e9 immerg\u00e9 accidentellement (partiellement ou totalement) dans un liquide (eau, th\u00e9, caf\u00e9, jus ou autre) ?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false,
                    "responsive": true
                },
                "options": [
                    {
                        "label": "Oui",
                        "checked": false
                    },
                    {
                        "label": "Non",
                        "checked": false
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "col-1"
                }
            },
            "id": "f16",
            "cid": "c63"
        },
        {
            "label": "Prestation de service",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false,
                    "responsive": true
                }
            },
            "id": "f17",
            "cid": "c69"
        },
        {
            "label": "Service demand\u00e9",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false,
                    "responsive": true
                },
                "options": [
                    {
                        "label": "R\u00e9paration (logicielle\/mat\u00e9rielle)*",
                        "checked": false
                    },
                    {
                        "label": "R\u00e9cup\u00e9ration du contenu num\u00e9rique (documents, photos, contacts, etc.)",
                        "checked": false
                    }
                ],
                "presetJson": "",
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Ce champ est requis."
                    }
                },
                "style": {
                    "columns": "col-1"
                },
                "description": "*  Si l'appareil a \u00e9t\u00e9 immerg\u00e9 accidentellement (partiellement ou totalement) dans un liquide (eau, th\u00e9, caf\u00e9, jus ou autre), son int\u00e9gralit\u00e9 fonctionnelle ne pourra pas \u00eatre garantie. Dans un tel cas, la r\u00e9cup\u00e9ration du contenu num\u00e9rique (documents, photos, contacts, etc.) de l'appareil est recommand\u00e9e."
            },
            "id": "f18",
            "cid": "c77"
        },
        {
            "label": "Si l'appareil ne peut pas \u00eatre r\u00e9par\u00e9 ou son contenu num\u00e9rique impossible \u00e0 r\u00e9cup\u00e9rer, quelle option pr\u00e9f\u00e9rez-vous ?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false,
                    "responsive": true
                },
                "options": [
                    {
                        "label": "R\u00e9assembler et me retourner l'appareil (frais de retour applicables)",
                        "checked": false
                    },
                    {
                        "label": "Recycler (de mani\u00e8re confidentielle et s\u00e9curitaire) l'ensemble de l'appareil (sans frais)\u2020",
                        "checked": false
                    }
                ],
                "presetJson": "",
                "description": "\u2020  Le recyclage (de mani\u00e8re confidentielle et s\u00e9curitaire) de l'appareil implique le retrait de la puce \u00e9lectronique contenant les donn\u00e9es personnelles et syst\u00e8me (crypt\u00e9es) et de sa destruction (physique - par concassage), puis \u00e0 la r\u00e9utilisation (\u00e0 l'interne) du reste de l'appareil \u00e0 des fins de recherche et d\u00e9veloppement ou \u00e0 son envoi (en partie ou en totalit\u00e9) dans un centre de recyclage de mat\u00e9riel \u00e9lectronique appropri\u00e9.",
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Ce champ est requis."
                    }
                },
                "style": {
                    "columns": "col-1"
                }
            },
            "id": "f19",
            "cid": "c82"
        },
        {
            "label": "Retour de l'appareil",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false,
                    "responsive": true
                },
                "hidden": true
            },
            "id": "f20",
            "cid": "c87"
        },
        {
            "label": "Quelle option d\u2019exp\u00e9dition d\u00e9sirez-vous pour le retour de votre appareil ?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false,
                    "responsive": true
                },
                "options": [
                    {
                        "label": "Standard : 20 $ CA (3 \u00e0 4 jours ouvrables)",
                        "checked": false,
                        "value": ""
                    },
                    {
                        "label": "Express : 50 $ CA (1 jour ouvrable)",
                        "checked": false
                    }
                ],
                "presetJson": "",
                "hidden": true,
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Ce champ est requis."
                    }
                },
                "style": {
                    "columns": "col-1"
                }
            },
            "id": "f21",
            "cid": "c94"
        },
        {
            "label": "Code d'acc\u00e8s (de l'appareil)",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false,
                    "responsive": true
                }
            },
            "id": "f22",
            "cid": "c99"
        },
        {
            "label": "Code d'acc\u00e8s (mot de passe)",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false,
                    "responsive": true
                },
                "size": "small",
                "addon": [],
                "description": "Requis pour les essais fonctionnels (apr\u00e8s r\u00e9paration) ou la r\u00e9cup\u00e9ration du contenu num\u00e9rique (documents, photos, contacts, etc.) de l'appareil.\n\nNOTE : Cette information peut \u00e9galement \u00eatre transmise ult\u00e9rieurement par courriel ou t\u00e9l\u00e9phone.\n\nNE PAS INCLURE LE CODE D'ACC\u00c8S DANS L'ENVOI (COLIS) DE VOTRE APPAREIL.",
                "validators": {
                    "required": {
                        "enabled": false
                    },
                    "alphanumeric": {
                        "enabled": false
                    }
                },
                "mask": {
                    "pattern": ""
                }
            },
            "id": "f23",
            "cid": "c104"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Submit",
                    "labelPrev": "< Back",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "ENVOYER",
                "icon": "",
                "checkRequiredFields": "V\u00e9rifiez les champs requis."
            },
            "id": "f0",
            "cid": "c0"
        }
    ],
    "gdpr": {
        "consentFieldId": "",
        "saveData": "no"
    },
    "licenseKey": "",
    "lang": {
        "language": "fr"
    }
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class